services:
  mysqldb:
    image: mysql:8.3.0
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=stationSki
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql

  stock-service:
    depends_on:
      - mysqldb
    image: kaibirihab/rihabimage
    restart: on-failure
    ports:
      - 8090:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "",
        "spring.jpa.hibernate.ddl-auto": "update",
        "server.servlet.context-path": "/api",
        "server.port": 8089,
        "spring.jpa.show-sql": true,
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
        "logging.level.root": "info",
        "logging.pattern.console": "= %d{yyyy-MM-dd HH:mm:ss} -  %-5level- %logger{45} - %msg %n"
      }'
    stdin_open: true
    tty: true
  angular-app:
    image: kaibirihab/rihabimagefront
    container_name: docker-compose-angular-app
    ports:
      - "4200:80"
    depends_on:
      - stock-service
volumes:
  db:
